language: c

dist: xenial

branches:
  only:
    - master
jobs:
  fast_finish: true
  include:
    - os: linux
      language: c
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8" CF=-DBUILD_SHARED_LIBS=OFF
    - os: linux
      language: c
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8" CF=-DBUILD_SHARED_LIBS=ON
    - os: osx
      language: c
      env:
        - MATRIX_EVAL="CC=clang" CF=-DBUILD_SHARED_LIBS=ON
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm;
        wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -;
        sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list;
        sudo apt-get update; sudo apt-get install -y pvs-studio
    fi
script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake .. "${CF}"
  - cmake --build .
  - cpack
